version: "3"

services:
  db:
    image: mysql
    volumes:
      - 'dbdata:/var/lib/mysql'
      - './mysql_conf:/etc/mysql/conf.d'
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
  app:
    build:
      context: .
      args:
        - USERID=1000
    image: rails-project:20190622
    command: su -c "bundle exec rails s -p 3000 -b 0.0.0.0" app
    environment:
      - RAILS_ENV=development
      - DATABSE_HOST=db
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    depends_on:
      - 'db'

volumes:
  dbdata:
